apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-cluster-dev
  namespace: flux-system
spec:
  interval: 1m0s 
  path: ../../../development/kustomization.yaml  
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
