apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-cluster-prod
  namespace: flux-system
spec:
  interval: 10m0s 
  path: production 
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
