apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: mod04-less13
commonLabels:
  app: course-app
images:
- name: rdlsolutions/course-app
  newTag: "2.0.0"
