apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: app-dev
spec:
  interval: 1m0s 
  path: "./course-app/overlays/development/kustomization.yaml"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system