apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: my-cluster-dev
  namespace: flux-system
spec:
  interval: 10m0s 
  path: overlays/development  
  prune: true
  sourceRef:
    kind: GitRepository
    name: rd-fluxcd-lesson
